# URLs to websites for downloads
BIBGED_URL:
  - 'https://frigg.uio.no/JASPAR/JASPAR_TFBSs/{year}/JASPAR{year}_{genome_assembly}.bb'
  - 'http://expdata.cmmt.ubc.ca/JASPAR/downloads/UCSC_tracks/{year}/JASPAR{year}_{genome_assembly}.bb'
MOTIF_URL:
  - 'https://frigg.uio.no/JASPAR/JASPAR_TFBSs/{year}/{genome_assembly}/'
  - 'http://expdata.cmmt.ubc.ca/JASPAR/downloads/UCSC_tracks/{year}/{genome_assembly}/'
ENSEMBL_URL: 'http://www.ensembl.org/biomart'
ENSEMBL_REST: 'https://rest.ensembl.org'
MAPPING_URL: 'https://rest.uniprot.org/idmapping/'
STRING_URL: 'https://string-db.org/api/tsv/'
NCBI_URL: 'https://api.ncbi.nlm.nih.gov/datasets/v2alpha/'
HG_CHROMOSOME_URL: 'https://hgdownload.soe.ucsc.edu/goldenPath/{genome_assembly}/database/chromAlias.txt.gz'

# Synonyms for genome assembly versions
ASSEMBLY_SYNONYM:
  GRCh38: 'hg38'
  GRCh37: 'hg19'
  T2T-CHM13v2.0: 'hs1'

# Default chromosomes to use
DEFAULT_CHROMOSOMES: [
  'chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8',
  'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16',
  'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY'
]

# Default chromosome name mapping from Ensembl to UCSC
DEFAULT_MAPPING:
  '1': 'chr1'
  '2': 'chr2'
  '3': 'chr3'
  '4': 'chr4'
  '5': 'chr5'
  '6': 'chr6'
  '7': 'chr7'
  '8': 'chr8'
  '9': 'chr9'
  '10': 'chr10'
  '11': 'chr11'
  '12': 'chr12'
  '13': 'chr13'
  '14': 'chr14'
  '15': 'chr15'
  '16': 'chr16'
  '17': 'chr17'
  '18': 'chr18'
  '19': 'chr19'
  '20': 'chr20'
  '21': 'chr21'
  '22': 'chr22'
  'X': 'chrX'
  'Y': 'chrY'
  'MT': 'chrM'