default_workflow: False  # True by default
on_the_fly_processing: False  # False by default
genome_assembly: "hg38"
motif:
  jaspar_release: "JASPAR2024"  # Default is newest release
  tfbs_file: "publication_priors/2024/.sponge_temp/JASPAR.bb"
  # If neither tf_names nor matrix_ids are specified,
  # all vertebrate TFs are selected
  # tf_names:
  # matrix_ids:
  unique_motifs: False  # False by default
  drop_heterodimers: True  # True by default
region:
  # region_file:
  filter_basic: True  # True by default
  # If chromosomes is not defined: all autosomes + X, Y
  # If chromosomes is specified as empty (None): all chromosomes
  # chromosomes:
  tss_offset: [-750, 250]
filter:
  n_processes: 16
  score_threshold: 400
ppi:
  physical_only: True  # True by default
motif_output:
  file_name: ".refactor_temp_2024/motif_prior.tsv"
  use_gene_names: True  # True by default
  protein_coding_only: False  # False by default
  weighted: False  # False by default
ppi_output:
  file_name: ".refactor_temp_2024/ppi_prior.tsv"
  weighted: False  # False by default