default_workflow: False  # True by default
on_the_fly_processing: False
genome_assembly: "hg38"
motif:
  jaspar_release: "JASPAR2024"
  tfbs_file: "publication_priors/2024/.sponge_temp/JASPAR.bb"
  tf_names: ["SOX2", "GATA2", "MYC"]
  # matrix_ids:
  unique_motifs: False
  drop_heterodimers: True
region:
  # region_file:
  filter_basic: True
  # If chromosomes is not defined: all autosomes + X, Y
  # If chromosomes is defined as empty (None): all chromosomes
  chromosomes: ["chr19"]
  tss_offset: [-750, 250]
filter:
  n_processes: 16
  score_threshold: 400