name: SPONGE test on a combination of Python versions and OS

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  os-python-compatibility:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        python: [ '3.9', '3.10', '3.11' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Check Python version
      run: |
        which python3
        python3 --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install -e .

    - name: Run the tests
      run: pytest tests -m 'not slow'
